name: Downloader
on:
  schedule:
    - cron: "58 * * * *"
    - cron: "15 * * * *"
    - cron: "30 * * * *"
    - cron: "45 * * * *"
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Prague
      - name: Download
        run: python downloader.py
      - name: Save
        uses: EndBug/add-and-commit@v4
        with:
          add: data
          author_name: downloader
          author_email: ${{ secrets.AUTHOR_EMAIL }}
          message: Add data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
