name: Publisher
on:
  schedule:
    - cron: "5 * * * *"
    - cron: "35 * * * *"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('publisher_requirements.txt') }}
      - name: Install requirements
        run: pip install -r publisher_requirements.txt
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Prague
      - name: Publish
        run: python publisher.py
      - name: Save
        uses: EndBug/add-and-commit@v4
        with:
          add: index.html 24h.html
          author_name: publisher
          author_email: ${{ secrets.AUTHOR_EMAIL }}
          message: Publish page
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
